const fractions = {
  "1/2": "50%",
  "1/3": "33.333333%",
  "2/3": "66.666667%",
  "1/4": "25%",
  "2/4": "50%",
  "3/4": "75%",
  "1/5": "20%",
  "2/5": "40%",
  "3/5": "60%",
  "4/5": "80%",
  "1/6": "16.666667%",
  "2/6": "33.333333%",
  "3/6": "50%",
  "4/6": "66.666667%",
  "5/6": "83.333333%",
  "1/12": "8.333333%",
  "2/12": "16.666667%",
  "3/12": "25%",
  "4/12": "33.333333%",
  "5/12": "41.666667%",
  "6/12": "50%",
  "7/12": "58.333333%",
  "8/12": "66.666667%",
  "9/12": "75%",
  "10/12": "83.333333%",
  "11/12": "91.666667%",
};

const screens = {
  "sm-n-above": "(min-width: 600px)",
  "md-n-above": "(min-width: 768px)",
  "lg-n-above": "(min-width: 992px)",
  "xl-n-above": "(min-width: 1280px)",
  "sm-n-below": "(max-width: 600px)",
  "md-n-below": "(max-width: 768px)",
  "lg-n-below": "(max-width: 992px)",
  "xl-n-below": "(max-width: 1280px)",
  "sm-only": "(min-width: 0px) and (max-width: 600px)",
  "md-only": "(min-width: 600px) and (max-width: 768px)",
  "lg-only": "(min-width: 768px) and (max-width: 992px)",
  "xl-only": "(min-width: 992px) and (max-width: 1280px)",
};

const theme = {
  screens: Object.keys(screens).reduce((acc, screen) => {
    acc[screen] = { raw: `(--${screen})` };
    return acc;
  }, {}),
  colors: {
    inherit: "inherit",
    current: "currentColor",
    transparent: "transparent",
    // primary
    "primary-brand": "var(--primary-brand)",
    "primary-brand-accessible": "var(--primary-brand-accessible)",
    "primary-black": "var(--primary-black)",
    "primary-white": "var(--primary-white)",

    //grays
    "gray-1": "var(--gray-1)",
    "gray-2": "var(--gray-2)",
    "gray-3": "var(--gray-3)",
    "gray-4": "var(--gray-4)",
    "gray-5": "var(--gray-5)",
    "gray-6": "var(--gray-6)",
    "gray-7": "var(--gray-7)",
    "gray-8": "var(--gray-8)",
    "gray-9": "var(--gray-9)",

    // functional
    "functional-red": "var(--functional-red)",
    "functional-blue": "var(--functional-blue)",
    "functional-green": "var(--functional-green)",
    "functional-yellow": "var(--functional-yellow)",

    // supporting
    "supporting-green-1": "var(--supporting-green-1)",
    "supporting-green-2": "var(--supporting-green-2)",
    "supporting-green-3": "var(--supporting-green-3)",
    "supporting-purple-1": "var(--supporting-purple-1)",
    "supporting-purple-2": "var(--supporting-purple-2)",
    "supporting-purple-3": "var(--supporting-purple-3)",
    "supporting-blue-1": "var(--supporting-blue-1)",
    "supporting-blue-2": "var(--supporting-blue-2)",
    "supporting-blue-3": "var(--supporting-blue-3)",
    "supporting-pink-1": "var(--supporting-pink-1)",
    "supporting-pink-2": "var(--supporting-pink-2)",
    "supporting-pink-3": "var(--supporting-pink-3)",
    "supporting-yellow-1": "var(--supporting-yellow-1)",
    "supporting-yellow-2": "var(--supporting-yellow-2)",
    "supporting-yellow-3": "var(--supporting-yellow-3)",
  },
  columns: {
    auto: "var(--columns-auto)",
    1: "var(--columns-1)",
    2: "var(--columns-2)",
    3: "var(--columns-3)",
    4: "var(--columns-4)",
    5: "var(--columns-5)",
    6: "var(--columns-6)",
    7: "var(--columns-7)",
    8: "var(--columns-8)",
  },
  spacing: {
    0: "var(--spacing-0)",
    microgap: "var(--spacing-microgap)",
    smallgap: "var(--spacing-smallgap)",
    1: "var(--spacing-1)",
    2: "var(--spacing-2)",
    3: "var(--spacing-3)",
    4: "var(--spacing-4)",
    5: "var(--spacing-5)",
    6: "var(--spacing-6)",
    8: "var(--spacing-8)",
    10: "var(--spacing-10)",
    12: "var(--spacing-12)",
    16: "var(--spacing-16)",
    20: "var(--spacing-20)",
  },
  aspectRatio: {
    auto: "var(--ratio-auto)",
    square: "var(--ratio-square)",
    landscape: "var(--ratio-landscape)",
    portrait: "var(--ratio-portrait)",
    widescreen: "var(--ratio-widescreen)",
    ultrawide: "var(--ratio-ultrawide)",
    golden: "var(--ratio-golden)",
  },
  blur: {
    0: "var(--blur-0)",
    1: "var(--blur-4)",
    2: "var(--blur-8)",
    3: "var(--blur-12)",
    4: "var(--blur-16)",
    5: "var(--blur-24)",
    6: "var(--blur-40)",
    7: "var(--blur-64)",
  },
  borderColor: ({ theme }) => ({
    ...theme("colors"),
    DEFAULT: theme("currentColor"),
  }),
  borderRadius: {
    0: "var(--radius-0)",
    1: "var(--radius-1)",
    2: "var(--radius-2)",
    3: "var(--radius-3)",
    4: "var(--radius-4)",
    full: "var(--radius-full)",
  },
  borderWidth: {
    0: "var(--border-size-0)",
    1: "var(--border-size-1)",
    2: "var(--border-size-2)",
    3: "var(--border-size-3)",
    4: "var(--border-size-4)",
  },
  boxShadow: false,
  dropShadow: false,
  fontSize: {
    "000": ["var(--font-size-000)", { lineHeight: "0.75rem" }],
    "00": ["var(--font-size-00)", { lineHeight: "0.875rem" }],
    0: ["var(--font-size-0)", { lineHeight: "1rem" }],
    1: ["var(--font-size-1)", { lineHeight: "1.125rem" }],
    "1+relaxed": ["var(--font-size-1)", { lineHeight: "1.5rem" }],
    2: ["var(--font-size-2)", { lineHeight: "1.25rem" }],
    "2+relaxed": ["var(--font-size-2)", { lineHeight: "1.6875rem" }],
    3: ["var(--font-size-3)", { lineHeight: "1.375rem" }],
    "3+relaxed": ["var(--font-size-3)", { lineHeight: "1.875rem" }],
    4: ["var(--font-size-4)", { lineHeight: "1.625rem" }],
    5: ["var(--font-size-5)", { lineHeight: "2.125rem" }],
    6: ["var(--font-size-6)", { lineHeight: "1" }],
    7: ["var(--font-size-7)", { lineHeight: "1" }],
    8: ["var(--font-size-8)", { lineHeight: "1" }],
    9: ["var(--font-size-9)", { lineHeight: "1" }],
  },
  fontWeight: {
    normal: "var(--font-normal)",
    bold: "var(--font-bold)",
  },
  fontFamily: {
    "brans-sans": "var(--font-brand-sans)",
    "os-sans": "var(--font-os-sans)",
    "os-serif": "var(--font-os-serif)",
    "os-mono": "var(--font-os-mono)",
  },
  letterSpacing: false,
  lineHeight: false,
  height: ({ theme }) => ({
    auto: "auto",
    ...theme("spacing"),
    ...fractions,
    full: "var(--size-full)",
    min: "var(--size-min)",
    max: "var(--size-max)",
    fit: "var(--size-fit)",
    screen: "var(--size-screen-block)",
  }),
  width: ({ theme }) => ({
    auto: "auto",
    ...theme("spacing"),
    ...fractions,
    full: "var(--size-full)",
    min: "var(--size-min)",
    max: "var(--size-max)",
    fit: "var(--size-fit)",
    screen: "var(--size-screen-inline)",
  }),
  maxHeight: ({ theme }) => ({
    ...theme("spacing"),
    ...fractions,
    none: "var(--size-none)",
    0: "var(--size-0)",
    full: "var(--size-full)",
    min: "var(--size-min)",
    max: "var(--size-max)",
    fit: "var(--size-fit)",
    screen: "var(--size-screen-block)",
  }),
  maxWidth: ({ theme }) => ({
    none: "var(--size-none)",
    ...fractions,
    ...theme("spacing"),
    0: "var(--size-0)",
    full: "var(--size-full)",
    min: "var(--size-min)",
    max: "var(--size-max)",
    fit: "var(--size-fit)",
    screen: "var(--size-screen-inline)",
  }),
  order: {
    first: "var(--order-first)",
    last: "var(--order-last)",
    0: "var(--order-0)",
    1: "var(--order-1)",
    2: "var(--order-2)",
    3: "var(--order-3)",
    4: "var(--order-4)",
    5: "var(--order-5)",
  },
};

module.exports = { theme, screens };
